### ISSUE TITLE
Patcher

### ISSUE THREAD

**Issue by devCanario** [AntidetectBrowser/ChromeDriverBypassCloudflareForWindow#1]
How did you do this, can you show the code or the proccess you did to patch it?
and how did you find it

**Comment by JoyNath1337** [comment]
He should keep it encrypted, cloudflare employees won't be able to fix it :)

**Comment by AntidetectBrowser** [comment]
> He should keep it encrypted, cloudflare employees won't be able to fix it :)

hahahaha, it is  assembly,i didnot encrypted it

**Comment by leesanghyone** [comment]
"I am a person learning to code, and I admire you. 
I want to ask what I need to learn to create an antidetector browser like you.

JavaScript?
Reversing?
C++?"

**Comment by leesanghyone** [comment]
"I am a person learning to code, and I admire you.
 I want to ask what I need to learn to create an antidetector browser like you.

JavaScript?
Reversing?
C++?"

**Comment by dadimmym** [comment]
thanks for such a nice job!!!

**Comment by saeidsedqi** [comment]
Great job. Thanks

**Comment by dadimmym** [comment]
my chrome version is 115.0.5790.171, your driver is 115.0.5790.75

**Comment by dadimmym** [comment]
my chrome version is 115.0.5790.171, your driver is 115.0.5790.75. would you make a new version? thanks a lot!
